create table Flight (airline char(32), origin char(32), destination char(32) ) ;
INSERT INTO Flight VALUES('Delta','Aberdeen','London Gatwick');
INSERT INTO Flight VALUES('Delta','Aberdeen','London Heathrow');
INSERT INTO Flight VALUES('Delta','Alicante, Spain','London Heathrow');
INSERT INTO Flight VALUES('Delta','Amsterdam, N/lands','Barcelona, Spain');
INSERT INTO Flight VALUES('Delta','Amsterdam, N/lands','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Amsterdam, N/lands','Faro, Portugal');
INSERT INTO Flight VALUES('Delta','Amsterdam, N/lands','Frankfurt, Germany');
INSERT INTO Flight VALUES('Delta','Amsterdam, N/lands','Houston Intl,Tx,USA');
INSERT INTO Flight VALUES('Delta','Amsterdam, N/lands','Las Palmas, Canaries');
INSERT INTO Flight VALUES('Delta','Aruba, Neth Antilles','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','Barcelona, Spain','Dublin, Ireland');
INSERT INTO Flight VALUES('Delta','Barcelona, Spain','Dusseldorf, Germany');
INSERT INTO Flight VALUES('Delta','Barcelona, Spain','Manchester Intl');
INSERT INTO Flight VALUES('Delta','Basle, Switzerland','London Heathrow');
INSERT INTO Flight VALUES('Delta','Belfast, N. Ireland','London Heathrow');
INSERT INTO Flight VALUES('Delta','Belgrade, Serbia','London Gatwick');
INSERT INTO Flight VALUES('Delta','Berlin, Tegel Apt','London Heathrow');
INSERT INTO Flight VALUES('Delta','Bilbao, Spain','Brussels Zaventem');
INSERT INTO Flight VALUES('Delta','Birmingham Intl','Barcelona, Spain');
INSERT INTO Flight VALUES('Delta','Birmingham Intl','Edinburgh');
INSERT INTO Flight VALUES('Delta','Bologna, Italy','London Heathrow');
INSERT INTO Flight VALUES('Delta','Boston, Mass., USA','London Gatwick');
INSERT INTO Flight VALUES('Delta','Bremen, Germany','Fuerteventura,Canar.');
INSERT INTO Flight VALUES('Delta','Bristol, Lulsgate','Brussels Zaventem');
INSERT INTO Flight VALUES('Delta','Brussels Zaventem','Atlanta, Geo, USA');
INSERT INTO Flight VALUES('Delta','Brussels Zaventem','Barcelona, Spain');
INSERT INTO Flight VALUES('Delta','Brussels Zaventem','Bilbao, Spain');
INSERT INTO Flight VALUES('Delta','Brussels Zaventem','Bristol, Lulsgate');
INSERT INTO Flight VALUES('Delta','Brussels Zaventem','Chicago,OHare,Il');
INSERT INTO Flight VALUES('Delta','Cancun, Mexico','Cologne, Germany');
INSERT INTO Flight VALUES('Delta','Cincinnati, USA','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Cologne, Germany','Cancun, Mexico');
INSERT INTO Flight VALUES('Delta','Cologne, Germany','Ciego De Avila Cuba');
INSERT INTO Flight VALUES('Delta','Cologne, Germany','East Midlands');
INSERT INTO Flight VALUES('Delta','Copenhagen, Kastrup','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Dallas, Tx, USA','London Gatwick');
INSERT INTO Flight VALUES('Delta','Damascus, Syria','London Heathrow');
INSERT INTO Flight VALUES('Delta','Detroit, Mich, USA','Frankfurt, Germany');
INSERT INTO Flight VALUES('Delta','Dubai, U. A. E.','London Heathrow');
INSERT INTO Flight VALUES('Delta','Dublin, Ireland','Barcelona, Spain');
INSERT INTO Flight VALUES('Delta','Dusseldorf, Germany','Barcelona, Spain');
INSERT INTO Flight VALUES('Delta','Dusseldorf, Germany','Palma, Majorca');
INSERT INTO Flight VALUES('Delta','East Midlands','Cologne, Germany');
INSERT INTO Flight VALUES('Delta','East Midlands','Philadelphia, USA');
INSERT INTO Flight VALUES('Delta','Edinburgh','Birmingham Intl');
INSERT INTO Flight VALUES('Delta','Faro, Portugal','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Calgary, Canada');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Detroit, Mich, USA');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Guernsey, Channel Is');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','London City');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Los Angeles, USA');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Porto, Portugal');
INSERT INTO Flight VALUES('Delta','Frankfurt, Germany','Tampa, Fl, USA');
INSERT INTO Flight VALUES('Delta','Fuerteventura,Canar.','Bremen, Germany');
INSERT INTO Flight VALUES('Delta','Fuerteventura,Canar.','Hannover, Germany');
INSERT INTO Flight VALUES('Delta','Fuerteventura,Canar.','Helsinki, Finland');
INSERT INTO Flight VALUES('Delta','Geneva, Switzerland','JFK, New York');
INSERT INTO Flight VALUES('Delta','Geneva, Switzerland','London Heathrow');
INSERT INTO Flight VALUES('Delta','Glasgow, Scotland','Birmingham Intl');
INSERT INTO Flight VALUES('Delta','Gothenburg, Sweden','London Gatwick');
INSERT INTO Flight VALUES('Delta','Guernsey, Channel Is','Frankfurt, Germany');
INSERT INTO Flight VALUES('Delta','Hamburg, Germany','Atlanta, Geo, USA');
INSERT INTO Flight VALUES('Delta','Hannover, Germany','Fuerteventura,Canar.');
INSERT INTO Flight VALUES('Delta','Harare, Zimbabwe','London Gatwick');
INSERT INTO Flight VALUES('Delta','Helsinki, Finland','Fuerteventura,Canar.');
INSERT INTO Flight VALUES('Delta','Houston Intl,Tx,USA','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','Huntsville, Al, USA','Luxembourg');
INSERT INTO Flight VALUES('Delta','Islamabad, Pakistan','Manchester Intl');
INSERT INTO Flight VALUES('Delta','Istanbul, Turkey','London Heathrow');
INSERT INTO Flight VALUES('Delta','Jersey, Channel Is.','London Heathrow');
INSERT INTO Flight VALUES('Delta','JFK, New York','Athens, Greece');
INSERT INTO Flight VALUES('Delta','JFK, New York','Brussels Zaventem');
INSERT INTO Flight VALUES('Delta','JFK, New York','Geneva, Switzerland');
INSERT INTO Flight VALUES('Delta','JFK, New York','Rome, Fiumicino Apt.');
INSERT INTO Flight VALUES('Delta','Kiev, Borispool, Ukr','London Gatwick');
INSERT INTO Flight VALUES('Delta','Krakow, Poland','London Gatwick');
INSERT INTO Flight VALUES('Delta','Kuala Lumpur, Malay.','London Heathrow');
INSERT INTO Flight VALUES('Delta','Las Palmas, Canaries','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','LBP, Toronto, Canada','London Heathrow');
INSERT INTO Flight VALUES('Delta','Leeds/Bradford','Brussels Zaventem');
INSERT INTO Flight VALUES('Delta','Leipzig, Germany','London Heathrow');
INSERT INTO Flight VALUES('Delta','Lisbon, Portugal','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','London City','Frankfurt, Germany');
INSERT INTO Flight VALUES('Delta','London Gatwick','Aberdeen');
INSERT INTO Flight VALUES('Delta','London Heathrow','Aberdeen');
INSERT INTO Flight VALUES('Delta','London Heathrow','Geneva, Switzerland');
INSERT INTO Flight VALUES('Delta','London Heathrow','Munich, Germany');
INSERT INTO Flight VALUES('Delta','London Stansted','Barbados');
INSERT INTO Flight VALUES('Delta','London Stansted','Oslo, Fomebu Apt.');
INSERT INTO Flight VALUES('Delta','Los Angeles, USA','Frankfurt, Germany');
INSERT INTO Flight VALUES('Delta','Luxembourg','Huntsville, Al, USA');
INSERT INTO Flight VALUES('Delta','Luxembourg','London Heathrow');
INSERT INTO Flight VALUES('Delta','Lyon, France','London Heathrow');
INSERT INTO Flight VALUES('Delta','Madrid, Baraj, Spain','Stockholm, Arlanda');
INSERT INTO Flight VALUES('Delta','Malaga, Spain','Brussels Zaventem');
INSERT INTO Flight VALUES('Delta','Manchester Intl','Barcelona, Spain');
INSERT INTO Flight VALUES('Delta','Manchester Intl','Islamabad, Pakistan');
INSERT INTO Flight VALUES('Delta','Manchester Intl','Milan, Linate Apt.');
INSERT INTO Flight VALUES('Delta','Marseille, France','London Gatwick');
INSERT INTO Flight VALUES('Delta','Memphis, Ten., USA','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','Mexico City, Mexico','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Miami, Florida, USA','London Gatwick');
INSERT INTO Flight VALUES('Delta','Milan, Linate Apt.','Manchester Intl');
INSERT INTO Flight VALUES('Delta','Milan, Malpensa Apt.','Chicago,OHare,Il');
INSERT INTO Flight VALUES('Delta','Montego Bay, Jamaica','London Gatwick');
INSERT INTO Flight VALUES('Delta','Moscow, USSR','London Gatwick');
INSERT INTO Flight VALUES('Delta','Munich, Germany','London Heathrow');
INSERT INTO Flight VALUES('Delta','Munich, Germany','Washington Dulles');
INSERT INTO Flight VALUES('Delta','Naples, Italy','London Gatwick');
INSERT INTO Flight VALUES('Delta','Newark, Nj, USA','London Gatwick');
INSERT INTO Flight VALUES('Delta','Newcastle','London Heathrow');
INSERT INTO Flight VALUES('Delta','Nice, France','Atlanta, Geo, USA');
INSERT INTO Flight VALUES('Delta','Nuremberg, Germany','London Heathrow');
INSERT INTO Flight VALUES('Delta','Orlando AFB, Florida','London Gatwick');
INSERT INTO Flight VALUES('Delta','Orly, Paris','Atlanta, Geo, USA');
INSERT INTO Flight VALUES('Delta','Oslo, Fomebu Apt.','London Stansted');
INSERT INTO Flight VALUES('Delta','Ottawa, Canada','London Heathrow');
INSERT INTO Flight VALUES('Delta','Palma, Majorca','Dusseldorf, Germany');
INSERT INTO Flight VALUES('Delta','Philadelphia, USA','East Midlands');
INSERT INTO Flight VALUES('Delta','Pisa, Italy','London Gatwick');
INSERT INTO Flight VALUES('Delta','Porto, Portugal','Frankfurt, Germany');
INSERT INTO Flight VALUES('Delta','Prague, Czech','London Heathrow');
INSERT INTO Flight VALUES('Delta','Riyadh, Saudi Arabia','London Heathrow');
INSERT INTO Flight VALUES('Delta','Rome, Fiumicino Apt.','JFK, New York');
INSERT INTO Flight VALUES('Delta','Rotterdam, N/lands','Stuttgart, Germany');
INSERT INTO Flight VALUES('Delta','Tokyo, Narita Int Ja','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Tokyo, Narita Int Ja','London Heathrow');
INSERT INTO Flight VALUES('Delta','Toulouse, France','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Valencia, Spain','London Heathrow');
INSERT INTO Flight VALUES('Delta','Vancouver, Canada','Amsterdam, N/lands');
INSERT INTO Flight VALUES('Delta','Venice, Marco Polo','London Heathrow');
INSERT INTO Flight VALUES('Delta','Verona, Italy','London Gatwick');
INSERT INTO Flight VALUES('Delta','Vilnius, Lithuania','London Gatwick');
INSERT INTO Flight VALUES('Delta','Warsaw, Poland','London Heathrow');
INSERT INTO Flight VALUES('Delta','Washington Dulles','CDG, Paris, France');
INSERT INTO Flight VALUES('Delta','Washington Dulles','Munich, Germany');
INSERT INTO Flight VALUES('Delta','Woodford Manchester','Brussels Zaventem');
INSERT INTO Flight VALUES('Delta','Zurich, Switzerland','Atlanta, Geo, USA');
